[package]
name = "play-bitcoin-dev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdk = { version = "1.0.0-alpha.9", features = ["all-keys"] }
anyhow = "1.0.82"